# 100 creative company-first hooks — {co} = company name
HOOKS_100 = [
    "☕ *{co}* just opened a new role for you — come see & apply 👇",
    "🔥 *{co}* is hiring — your next move could start here 🚀",
    "👀 *{co}* posted a role that might fit you — check below",
    "📢 New from *{co}* — open the details & apply 👇",
    "✨ *{co}* has a fresh opening waiting for you 👀",
    "📞 Someone at *{co}* is looking for you — see the role below",
    "🚀 *{co}* wants talent like you — details below 👇",
    "💼 *{co}* dropped a new opportunity — worth a look 👀",
    "🎯 *{co}* is calling — new role alert below 📋",
    "⚡ Fresh role at *{co}* — scroll down & apply 👇",
    "😄 Plot twist: *{co}* might be your next company 👀",
    "🌟 *{co}* is open for a new hire — could it be you?",
    "👇 Stop scrolling — *{co}* has something for you",
    "🔔 *{co}* just listed a new opening — details below",
    "💡 *{co}* is looking for someone like you — apply below 👇",
    "☀️ Good morning! *{co}* has a new role open for you 👀",
    "🌅 Rise & shine — *{co}* is hiring today 🚀",
    "🍽️ Lunch break? *{co}* just posted a fresh opening 👇",
    "🌆 Evening update — *{co}* has a new role for you 👀",
    "🌙 Night drop from *{co}* — check before tomorrow 👇",
    "🍿 Netflix can wait — *{co}* is hiring tonight 😄",
    "📲 Your feed stops here — *{co}* wants you to see this 👀",
    "🏃 Don't walk — *{co}* has a role worth running for 👇",
    "💫 Today's pick: a new opening at *{co}* — see below",
    "🎉 Surprise! *{co}* posted a role that matches your vibe 👀",
    "👋 Hey — *{co}* is hiring and this one looks interesting 👇",
    "🔍 Found one for you: *{co}* just listed a new role 📋",
    "📌 Pin this — *{co}* has an opening you should see 👀",
    "🌈 Good news — *{co}* is actively hiring right now 🚀",
    "⏰ Right on time — *{co}* posted a role just for seekers like you 👇",
    "🎁 A little gift from us: fresh role at *{co}* — apply below 👀",
    "💪 You've got this — *{co}* has a new opening waiting 👇",
    "🧠 Smart move: check this new role at *{co}* 👀",
    "📈 Level up? *{co}* just posted something worth applying for 🚀",
    "🗓️ Today's highlight — *{co}* is hiring, details below 👇",
    "🔑 New key to your career? *{co}* opened a role — see below 👀",
    "🎤 Mic drop — *{co}* is hiring and you should know 👇",
    "🌍 Big name alert: *{co}* has a fresh opening for you 👀",
    "💬 Word on the street — *{co}* is looking for new talent 🚀",
    "🧭 Your next direction? *{co}* posted a role — check it 👇",
    "🏆 Top pick today: new opening at *{co}* 👀",
    "📣 Heads up! *{co}* just dropped a new job posting 👇",
    "🎬 New scene loading… *{co}* is hiring — tap below 👀",
    "🛎️ Ding! *{co}* has a new role on the board — see details 👇",
    "🔮 Could this be yours? *{co}* posted a fresh opening 👀",
    "🎵 New beat — *{co}* is hiring, check the role below 🚀",
    "📸 Snapshot: *{co}* wants someone like you — apply 👇",
    "🚦 Green light at *{co}* — new role, go apply 👀",
    "🧩 Missing piece? *{co}* might have your next role 👇",
    "🎓 Career move alert — *{co}* posted a new opening 👀",
    "💌 Special delivery from *{co}* — a role with your name on it 👇",
    "🌊 New wave at *{co}* — fresh hire alert, see below 👀",
    "🎪 Today's show: *{co}* is hiring — don't miss it 👇",
    "🔥 Hot listing — *{co}* just opened a new position 🚀",
    "🧲 Pulled this for you — *{co}* has a role worth seeing 👀",
    "🎯 Bullseye? *{co}* posted something that might fit you 👇",
    "🌸 Fresh bloom — *{co}* has a new opportunity today 👀",
    "🎨 New canvas at *{co}* — a role waiting for you 🚀",
    "🧳 Pack your ambition — *{co}* is hiring now 👇",
    "🎮 Next level unlocked? *{co}* posted a new role 👀",
    "📚 Chapter next — *{co}* has an opening for you 👇",
    "🌐 Trending hire: *{co}* listed a new role today 👀",
    "🎁 Unwrap this — *{co}* wants you to see their new opening 🚀",
    "🧃 Fresh squeeze — new role at *{co}*, details below 👇",
    "🎡 New ride at *{co}* — a career opportunity awaits 👀",
    "🔆 Bright spot today — *{co}* is actively hiring 👇",
    "🎤 Your cue — *{co}* posted a role, time to look 👀",
    "🧿 Good eye if you catch this — *{co}* is hiring 🚀",
    "🎈 Up and away — *{co}* has a new role for you 👇",
    "🌺 Blooming opportunity at *{co}* — check below 👀",
    "🎿 Slide into something new — *{co}* is hiring 👇",
    "🧵 New thread at *{co}* — a role you should read 👀",
    "🎇 Spark moment — *{co}* just posted a fresh opening 🚀",
    "🛸 Landed from *{co}* — new role alert below 👇",
    "🎹 New note from *{co}* — hiring update, see below 👀",
    "🧁 Sweet find — *{co}* has an opening today 👇",
    "🎯 On target — *{co}* listed a role worth your click 👀",
    "🌁 Clear view — *{co}* is hiring, details below 🚀",
    "🎳 Strike? *{co}* posted a role — roll down & apply 👇",
    "🧭 Compass says: look at this opening from *{co}* 👀",
    "🎪 Step right up — *{co}* has a new job posted 👇",
    "🔭 Spotted for you — *{co}* is hiring today 👀",
    "🎭 New act at *{co}* — a role just went live 🚀",
    "🧊 Cool find — *{co}* dropped a fresh opening 👇",
    "🎤 Encore! *{co}* has another role — see below 👀",
    "🌌 Star listing — *{co}* wants new talent like you 👇",
    "🎡 Spin of the day — new hire at *{co}* 👀",
    "🧩 Fit check — does this *{co}* role match you? See below 🚀",
    "🎬 Action! *{co}* posted a role — your move 👇",
    "🌻 Sunny news — *{co}* is hiring, open details below 👀",
    "🎸 New rhythm at *{co}* — fresh role alert 👇",
    "🧠 Brain food — *{co}* listed an opening worth reading 👀",
    "🎁 Today's catch — new role from *{co}* 🚀",
    "🌊 Ride the wave — *{co}* is hiring now 👇",
    "🎯 Aim here — *{co}* posted a role below 👀",
    "🧃 Refresh your search — *{co}* has something new 👇",
    "🎪 Main event: *{co}* opened a position today 👀",
    "🔥 Still reading? *{co}* is waiting — apply below 🚀",
    "🌟 Gold star listing — *{co}* is hiring 👇",
    "🎵 Turn it up — new opportunity at *{co}* 👀",
    "🧭 Next stop: *{co}* — they posted a role for you 👇",
    "🎁 Handpicked — *{co}* has a new opening today 👀",
]
